name: Build Alpha

run-name: Build Alpha

on:
  push:
    tags:
      - '*.*.*-alpha*'
      - '*.*.*-Alpha*'
    paths-ignore:
      - '.github/**'

jobs:
  package:
    name: Package Alpha
    uses: SFX-WoW/shared/.github/workflows/build-alpha.yml@main
