name: Release
on:
  push:
    tags:
      - '*.*.*'
      - '!*.*.*-*'

jobs:
  package:
    name: Package Releases
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone Project
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: |
          sudo apt-get install luarocks
          luarocks install --local luacheck

      - name: Run Luacheck
        run: /home/runner/.luarocks/bin/luacheck . -q

      - name: Package Release for Classic
        uses: BigWigsMods/packager@master
        with:
          args: -g 1.13.5 -m .pkgmeta-classic

      - name: Package Release for Retail
        uses: BigWigsMods/packager@master
